name: Deploy Static Frontend Buildedfile To Nginx Server

on:
  pull_request:
    branches:
      - for-deploy
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Setup VITE env variables
        run: |
          echo "VITE_BACKEND_URL=${{ vars.VITE_BACKEND_URL }}" >> .env

      - name: Install Dependencies and Build with Bun
        run: |
          bun i
          bun run build

      - name: Copy File to Nginx Server
        uses: appleboy/scp-action@master
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIV_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ./dist/
          target: ~/

          
      - name: Deploy to Nginx Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIV_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            bash test.sh
     
