name: Deploy Static Frontend Buildedfile To Nginx Server

on:
  pull_request:
    branches:
      - for-deploy
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          source ~/.bashrc
          ls -a ~
          export BUN_INSTALL=/home/runner/.bun

      - name: Setup VITE env variables
        run: |
          echo "VITE_BACKEND_URL=$VITE_BACKEND_URL" >> .env

      - name: Display None Toxic .env content
        run: |
          cat .env

      - name: Install dependencies and build with Bun
        run: |
          echo $BUN_INSTALL
          echo $BUN_INSTALL/bin/bun
          bun i   # Install dependencies with bun
          bun run build
          # $BUN_INSTALL/bin/bun build     # Build the project

      - name: Deploy to Nginx Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIV_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            bash test.sh
     
